# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-27 09:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_markdown.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Nothing', max_length=200, verbose_name='\u6807\u9898')),
                ('content', django_markdown.models.MarkdownField(blank=True, max_length=30000, verbose_name='\u6b63\u6587')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('author', models.CharField(default='\u65e0\u540d\u6c0f', max_length=50, verbose_name='\u4f5c\u8005')),
                ('blog_id', models.CharField(default=b'14802402663384413799364', max_length=100, unique=True, verbose_name='\u535a\u5ba2id')),
                ('subtitle', models.CharField(blank=True, max_length=100, verbose_name='\u526f\u6807\u9898')),
            ],
            options={
                'verbose_name': '\u535a\u5ba2',
                'verbose_name_plural': '\u535a\u5ba2\u7c7b',
            },
        ),
        migrations.CreateModel(
            name='BoardCommentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, max_length=400, verbose_name='\u5167\u5bb9')),
                ('comment_id', models.CharField(default=b'148024026633992497559764574614311', max_length=100, unique=True, verbose_name='\u8bc4\u8bba')),
                ('target_id', models.CharField(blank=True, max_length=100, verbose_name='\u76ee\u6807\u8bc4\u8bbaid')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('author', models.CharField(max_length=200, verbose_name='\u8bc4\u8bba\u8005\u540d\u79f0')),
            ],
            options={
                'verbose_name': '\u7559\u8a00\u677f',
                'verbose_name_plural': '\u7559\u8a00\u677f\u7c7b',
            },
        ),
        migrations.CreateModel(
            name='CommentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, max_length=400, verbose_name='\u5167\u5bb9')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('author', models.CharField(max_length=200, verbose_name='\u8bc4\u8bba\u8005\u540d\u79f0')),
                ('comment_id', models.CharField(default=b'1480240266338387101035131328', max_length=100, unique=True, verbose_name='\u8bc4\u8bbaid')),
                ('target_id', models.CharField(blank=True, max_length=100, verbose_name='\u76ee\u6807\u8bc4\u8bbaid')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='blog_comment', to='home.BlogModel', verbose_name='\u6240\u5c5e\u535a\u5ba2id')),
            ],
            options={
                'verbose_name': '\u8bc4\u8bba',
                'verbose_name_plural': '\u8bc4\u8bba\u7c7b',
            },
        ),
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(height_field='height', upload_to='/Users/gpxlcj/project/web_project/blog/media/img/', verbose_name='\u5c01\u9762\u56fe\u7247', width_field='width')),
                ('height', models.PositiveIntegerField(default=400, verbose_name='\u56fe\u7247\u9ad8\u5ea6')),
                ('width', models.PositiveIntegerField(default=700, verbose_name='\u56fe\u7247\u5bbd\u5ea6')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': '\u56fe\u7247\u7c7b',
            },
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='cover',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='home.ImageModel', verbose_name='\u5c01\u9762\u56fe\u7247'),
        ),
    ]
