# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='blog_id',
            field=models.CharField(default=b'148067284115567104794384453497', max_length=100, unique=True, verbose_name='\u535a\u5ba2id'),
        ),
        migrations.AlterField(
            model_name='boardcommentmodel',
            name='comment_id',
            field=models.CharField(default=b'1480672841156810724815328498', max_length=100, unique=True, verbose_name='\u8bc4\u8bba'),
        ),
        migrations.AlterField(
            model_name='commentmodel',
            name='comment_id',
            field=models.CharField(default=b'14806728411558191368535929', max_length=100, unique=True, verbose_name='\u8bc4\u8bbaid'),
        ),
    ]
