# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeoMongoDBModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_name', models.CharField(max_length=100, verbose_name='\u96c6\u5408\u540d\u7a31')),
                ('db_id', models.CharField(default=b'14806728411572333937791282763', max_length=100, unique=True, verbose_name='\u8cc7\u6599\u5eabid')),
                ('max_latitude', models.FloatField(default=0, verbose_name='\u6700\u5927\u7def\u5ea6')),
                ('min_latitude', models.FloatField(default=0, verbose_name='\u6700\u5c0f\u7def\u5ea6')),
                ('max_longitude', models.FloatField(default=0, verbose_name='\u6700\u5927\u7d93\u5ea6')),
                ('min_longitude', models.FloatField(default=0, verbose_name='\u6700\u5c0f\u7d93\u5ea6')),
                ('is_modified', models.BooleanField(default=False, verbose_name='\u8303\u56f4\u5df2\u77e5')),
            ],
            options={
                'verbose_name': '\u8cc7\u6599\u5eab',
                'verbose_name_plural': '\u8cc7\u6599\u5eab\u985e',
            },
        ),
    ]
